const recipeData = [
    {
    title: 'Burrito Bowls',
    desc: 'One of my all-time favorite go-to recipes is a flavorful and satisfying taco mince bowl. Seasoned with taco mix, the minced meat is served over a bed of fluffy rice, and complemented by creamy guacamole and a medley of fresh vegetables. This dish is quick to prepare, bursting with vibrant flavors, and a sure hit for any meal!',
    image: 'https://www.coles.com.au/content/dam/coles/cusp/recipes-inspiration/pvx/July-23-PVX-Burrito-Bowl-976x549.jpg',
    ingredient: [
      '500g beef mince',
      '20g taco seasoning mix',
      '1 1/2 cups red kidney beans',
      '1 1/2 cups rice',
      '1 avocado',
      '1/2 red onion',
      '1 lime',
      '1/4 cup coriander',
      '1 tomato',
      '2 cups lettuce',
      '1 cup corn',
    ],
    method: [
      'Peel avocado and cut into cubes. Finely dice red onion and coriander. Place into a bowl and add juice of 1 lime, salt, and pepper. Break up avocado and mix well. Set guacamole in fridge until ready to serve.',
      'Wash rice thoroughly and cook per instructions.',
      'While rice is cooking, heat oil in pan on medium-high heat. Add onion and cook until golden (1-2 minutes). Add beef mince, break it up and cook until browned.',
      'Add taco seasoning mix and water. Mix well and simmer for 10-15 minutes.',
      'Serve over rice and top with shredded lettuce, rinsed corn, diced tomato, and guacamole. Enjoy!',
    ],
    creator: 'Nathan',
    source: '',
    },
    {
    title: "Lola's Pork Adobo",
    desc: 'This recipe holds a special place in my heart, as it was passed down from my beloved Lola (grandma). The key to its irresistible flavor is marinating the pork overnight, allowing the vegeta to fully infuse the meat. Also adding vinegar before the other remaining ingredients. I absolutely love this dish for its delicious and tasty results. While I am currently refining this recipe, it remains a family favorite that never fails to impress.',
    image: 'https://images.unsplash.com/photo-1612156723470-10f426219f63?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredient: [
      '1 1/2 cups rice',
      '750 g pork rashers',
      '6 garlic cloves',
      '1 onion',
      '1/2 cup vinegar',
      '1/4 cup soy sauce',
      '3 bay leaves',
      '1 bunch lemongrass',
      '1/3 cup vegeta',
      '1 tbsp ground black peppercorns',
      '2 tbsp brown sugar',
    ],
    method: [
      'Marinate pork in vegeta for 12 hours or overnight.',
      'Wash rice thoroughly and start cooking per instructions.',
      'Place pot on medium-high heat, add oil and sauté onion until translucent. Add garlic and cook for 1 minute.',
      'Cook pork rashers until they completely change color.',
      'Add vinegar and let pot sit for 30 seconds. Then add soy sauce, bay leaves, lemongrass, and pepper. Mix well.',
      'Add boiling water and simmer until desired consistency is reached.',
      'Serve over rice and enjoy!',
    ],
    creator: 'My Lola',
    source: '',
    },
    {
    title: 'Lamb Saganaki',
    desc: 'Transform everyday ingredients into a culinary delight with this inspired lamb mince dish. These succulent lamb meatballs, crafted from simple pantry staples, are a guaranteed family pleaser. Simmered in a delicious tomato and white wine sauce, their rich, savory flavor and tender texture make them a standout at any meal, bringing a fresh twist to familiar favorites.',
    image: 'https://img.taste.com.au/ApaPQW0M/w720-h480-cfill-q80/taste/2016/11/lamb-meatball-saganaki-105732-1.jpeg',
    ingredient: [
      '500 g lamb mince',
      '1/2 packet risoni',
      '3/4 cup breadcrumbs',
      '1 egg',
      '1/4 cup oregano',
      '1 brown onion',
      '3 garlic cloves',
      '1/2 cup dry white wine',
      '400 g diced tomatoes',
      '1/2 cup beef stock',
      '50 g feta',
      'small bunch parsley',
    ],
    method: [
      'Bring pot of water to boil.',
      'Add risoni to salted boiling water, cook until done, then drain.',
      'In a bowl, combine mince, breadcrumbs, egg, oregano, and 1/3 of the onion. Season with salt and pepper. Mix well and roll into balls.',
      'Heat oil in pot over medium-high heat. Cook meatballs in batches, turning until browned all over. Set aside.',
      'Add oil if needed, sauté remaining onion until softened. Add garlic and cook for 1 minute.',
      'Add white wine, simmer and stir for 1 minute. Stir in diced tomatoes and beef stock. Return meatballs to pot, cover and simmer on low for 10 minutes.',
      'Serve meatballs over risoni. Optionally garnish with feta and parsley.',
    ],
    creator: 'Cathie Lonnie',
    source: 'https://www.taste.com.au/recipes/lamb-meatball-saganaki/94d2dd7a-f110-4cc8-8786-c5744f7c6d77',
    },
    {
    title: 'Vietnamese Pork Mince',
    desc: 'Simple dish, simple ingredients, elevated flavors—this Vietnamese pork mince recipe is a must-try. Bursting with vibrant and authentic tastes, it is an easy-to-make dish that delivers a delightful culinary experience. You do not want to pass on this recipe.',
    image: 'https://poshjournal.com/wp-content/uploads/2020/08/vietnamese-caramelized-pork-bowls-5.jpg',
    ingredient: [
      '500 g pork mince',
      '1 cup rice',
      '2 tsp ginger',
      '2 garlic cloves',
      '2 tbsp fish sauce',
      '3 tbsp brown sugar',
      'small bunch lemongrass',
      '1/2 brown onion',
      '1/2 cucumber',
      '1 tomato',
    ],
    method: [
      'Wash rice thoroughly and cook per instructions.',
      'Heat oil in pan, cook onion, ginger, and garlic for 2 minutes. Add pork mince and break up until cooked through.',
      'Add fish sauce, lemongrass, and brown sugar. Mix to combine and avoid stirring for 2 minutes to caramelize mince. Stir again and cook for another 30 seconds.',
      'Serve mince on a bed of rice and top with sliced cucumber, spring onion, and tomato. Enjoy!',
    ],
    creator: 'Nathan',
    source: '',
    },
    {
    title: 'Asian Glazed Salmon',
    desc: 'Indulge in the simplicity of this easy Asian glazed salmon. Marinate ahead of time for maximum flavor infusion, then enjoy the effortless cooking process that yields a dish bursting with savory-sweet goodness. With its straightforward steps and impressive taste, this recipe will not disappoint. Perfect for busy days or when you crave a delicious yet simple meal.',
    image: 'https://theresalwayspizza.com/assets/media/242Teriyaki%20Salmon.jpg',
    ingredient: [
      '500 g salmon fillet',
      '2 tsp ginger',
      '2 tsp garlic',
      '1 1/2 tbsp soy sauce',
      '2 tbsp oyster sauce',
      '2 tbsp sweet chilli sauce',
      'sesame seeds',
      'green onion',
      '1 cup rice',
    ],
    method: [
      'Whisk together ginger, garlic, soy sauce, oyster sauce, and sweet chilli sauce. Coat salmon with marinade. Cover and refrigerate for 30 minutes or overnight.',
      'Wash rice thoroughly and cook per instructions.',
      'Preheat oven to 180ºC. Bake salmon for 7 minutes, check and oil if necessary, then bake for a further 3 minutes.',
      'Serve salmon over rice, topped with sliced spring onion and sesame seeds. Enjoy!',
    ],
    creator: 'Nagi',
    source: 'https://www.recipetineats.com/asian-glazed-salmon/',
    },
    {
  title: 'Italian Rice Pilaf',
  desc: 'Experience the best of both worlds with this Italian beef rice pilaf—a delightful fusion of creamy risotto and rich Bolognese flavors. Tender beef, aromatic herbs, and savory tomato sauce come together harmoniously with perfectly cooked rice, creating a dish that embodies comfort and satisfaction. It is everything you love about risotto and Bolognese in one flavorful bite, making it a surefire hit for any meal.',
  image: 'https://everydayfamilyeats.com/wp-content/uploads/2024/03/Beef-Rice-Skillet-11.jpg',
  ingredient: [
    '500g beef mince',
    '1 1/2 cups rice',
    '2 tbsp olive oil',
    '2 garlic cloves, minced',
    '1 brown onion, diced',
    '1 carrot, diced',
    '1 celery stalk, diced',
    '1 1/2 tsp fennel seeds',
    '400g crushed tomatoes',
    '2 1/2 cups beef stock',
    '1 bay leaf',
    '2 tsp Worcestershire sauce',
    '2 tomatoes, diced',
  ],
  method: [
    'Heat oil in a large pot over high heat. Add garlic, onion, carrot, celery, and fennel seeds. Cook until onion is translucent.',
    'Add beef mince, breaking up until it turns from pink to brown. Season with salt and pepper.',
    'Add the unwashed rice and mix into the pot. Add remaining ingredients. Stir everything together, bring to a simmer, cover with lid and reduce heat to low (do not lift the lid).',
    'Cook for 22 minutes or until rice is tender. Remove from heat and rest, keeping covered, for 5 minutes—the rice will soften further.',
    'Serve with optional toppings and enjoy!',
  ],
  creator: 'Nagi',
  source: 'https://www.recipetineats.com/italian-beef-rice-pilaf/',
    },
    {
  title: 'Chicken Chickpea Salad',
  desc: 'Looking for a healthy, filling, and delicious meal that is easy to make? Look no further than this chicken chickpea salad. It is a definite addition to your meal rotation, offering a perfect balance of nutrients and flavors. You can easily substitute rotisserie chicken with shredded, seasoned chicken breast. Plus, keep an eye out for discounted rotisserie chickens at the end of the day for a real last-minute meal saver. Trust me, this salad is a winner!',
  image: 'https://images.unsplash.com/photo-1505576633757-0ac1084af824?q=80&w=2835&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  ingredient: [
    'Rotisserie chicken',
    '250g feta and olive blend',
    '1 can chickpeas',
    '1 can white beans',
    '1 bunch coriander',
    '1 bunch parsley',
    '1 punnet cherry tomatoes',
    '1 capsicum',
    '1/4 red onion',
    '1/2 cup olive oil',
    '1/4 cup red wine vinegar',
    '2 lemons',
    '1/2 tsp Dijon mustard',
    '2 garlic cloves',
    'Pinch of red pepper flakes',
  ],
  method: [
    'Break down and shred the chicken.',
    'In a big bowl, whisk together olive oil, red wine vinegar, lemon juice, Dijon mustard, salt, garlic, and red pepper flakes.',
    'Toss remaining ingredients in the bowl. Mix well. Taste and adjust salt and pepper. Enjoy!',
  ],
  creator: 'Violet Witchel',
  source: 'https://www.instagram.com/reel/C6Z17VFP6vt/?igsh=NGJyMXR3czBxOHRx',
    },
    {
  title: 'Cottage Cheese Sweet Potato Beef Bowl',
  desc: 'This powerhouse meal is loaded with healthy fats, complex carbs, and high protein. An incredibly simple 3-step meal — bound to be a staple in your household. Very customizable too! Feel free to swap out ground chicken or turkey for the beef. Season the meat and potatoes any way you like. Add more cottage cheese to each serving. Also, a fried egg on top would be insanely good!',
  image: 'https://www.5boysbaker.com/wp-content/uploads/2025/04/viral-cottage-cheese-sweet-potato-beef-bowl-681x1024.jpg',
  ingredient: [
    '2 tbsp olive oil',
    '500g beef mince',
    '2 sweet potatoes',
    '1 avocado',
    '300g cottage cheese',
    '2 tsp garlic powder',
    '2 tsp onion powder',
    '1 tsp smoked paprika',
  ],
  method: [
    'Preheat oven to 200ºC. Dice sweet potatoes into 2 cm cubes. Place on baking tray and toss with 1 tbsp olive oil, salt, and pepper. Cook for 15-20 minutes.',
    'Use remaining oil in a pan. Heat to medium-high and brown the beef. Add garlic powder, onion powder, smoked paprika, salt, and pepper. Mix well.',
    'In serving bowls, add sweet potato, beef mince, avocado, and cottage cheese.',
    'Optional: drizzle with honey, sriracha, or pickled chili jam.',
  ],
  creator: 'Nathan',
  source: '',
    },
    {
  title: 'Bacon Egg Avo Smash on Toast',
  desc: 'If your breakfast ever needed a glow-up, this is it. This dish takes humble boiled eggs and gives them a bold remix — stirred up with crispy bacon, smoky paprika, spicy sriracha, creamy kewpie mayo, tangy red onion, and a kiss of garlic. Spoon that flavor bomb over buttery toast topped with smashed avocado, and you have the kind of breakfast that makes regular avo toast feel insecure.',
  image: 'https://www.cookingforkeeps.com/wp-content/uploads/2019/05/Best-Avocado-Egg-Salad-Toast-4-1-730x1095.jpg',
  ingredient: [
    '3 eggs',
    '4 streaky bacon rashers',
    '1 avocado',
    '1/4 red onion',
    '1 garlic clove, grated',
    '1 tsp smoked paprika',
    '1 tbsp sriracha',
    '1 tbsp kewpie mayo',
    '2 slices bread, toasted',
    '1 tsp butter',
  ],
  method: [
    'Boil eggs for 8 minutes. Place in ice bath for 4 minutes. Peel eggs.',
    'Place bacon in a cold pan, heat to medium-high, and cook until crispy. Dice bacon and red onion finely. Combine bacon, red onion, sriracha, kewpie mayo, garlic, eggs, salt, pepper, and smoked paprika in a bowl. Mix until combined.',
    'Mash avocado to a spreadable consistency.',
    'Butter toast, spread avocado, and top with egg mixture.',
  ],
  creator: 'Bayashi TV',
  source: 'https://www.instagram.com/reel/Cknqnj3I_vX/?igsh=MTZldHE1ODFrNzRrZQ==',
    },
    {
  title: 'Satay Tofu with Lentil Turmeric Rice and Salad',
  desc: 'This bowl is all about bold flavors and feel-good fuel. Crispy baked satay tofu pairs perfectly with fluffy turmeric rice and hearty lentils — a combo that is both comforting and protein-packed. On the side, a refreshing salad mix which you can add your favourite dressing to.',
  image: 'https://food-guide.canada.ca/sites/default/files/2022-02/Spiced%20tofu%20and%20lentils%20with%20turmeric%20rice.jpg',
  ingredient: [
    '400g satay tofu',
    '425g lentils',
    '2 tsp turmeric',
    '2 tsp garlic powder',
    '1 1/2 cups rice',
    '120g spinach and rocket mix',
    '125g cherry tomatoes, halved',
    '1/4 red onion, finely diced',
    '1/4 cucumber, sliced',
    'Salad dressing of choice (optional, e.g., sesame dressing)',
  ],
  method: [
    'Preheat oven to 200ºC.',
    'Cut tofu into bite-sized pieces. Season with salt and pepper, then bake for 20-25 minutes.',
    'Wash rice and cook with turmeric, a pinch of salt, and garlic powder.',
    'Mix spinach, rocket, cherry tomatoes, red onion, cucumber, salt, pepper, and dressing.',
    'Wash lentils and add to the fluffed turmeric rice. Mix well. Serve with tofu and salad.',
  ],
  creator: 'Nathan',
  source: '',
    },
];
export default recipeData;