const recipeData = [
    {
        title: 'Burito Bowls',
        desc: 'Tasty easy weeknight meal.',
        image: 'https://www.coles.com.au/content/dam/coles/cusp/recipes-inspiration/pvx/July-23-PVX-Burrito-Bowl-976x549.jpg',
        ingredient: [
            'Rice',
            'Beef Mince',
            'Taco Seasoning',
            'Avocado',
            'Red Onion',
            'Lime',
            'Tomato',
            'Lettuce',
        ],
        method: [
            'Wash the rice thoroughly and start to cook.',
            'Meanwhile, oil pan on medium-high heat. Add your onion and cook till golden (1-2 min). Then add your beef mince, break up the beef mince and keep moving to ensure every bit of the mince browned.',
            'Add taco mix, water and mix in well. Let simmer for about 10-15 min',
            'Serve over the rice and add toppings of your choice. Enjoy!',
        ],
    },
    {
        title:`Lola's Pork Adobo`,
        desc:'The key is the marinate the pork overnight.',
        image:'https://images.unsplash.com/photo-1612156723470-10f426219f63?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ingredient: [
            'Rice',
            'Pork rashers',
            'Garlic',
            'Onion',
            'Vinegar',
            'Soy sauce',
            'Bay leaf',
            'Lemon grass',
            'Vegeta'
        ],
        method:[
            'Marinade pork in vegeta for 12 hours or overnight',
            'Cook rice',
            'Place pot on medium-high, add oil to sautee onion until translucent. Add garlic and cook for 1 minute further.',
            'Add pork until it completly changes colour',
            'Add vinegar and mix to combine, let the pot sit for 30 seconds. Then add soy sauce, bay leaves, lemongrass and pepper. Mix till combined well.',
            'Add boiling water then simmer until you reach desired thickness',
            'Serve over rice and enjoy!'
        ],
    },
    {
        title: 'Lamb Saganaki',
        desc:'A meal using everyday ingredients in a new and inspired way - meatballs are a guaranteed family pleaser.',
        image:'https://img.taste.com.au/ApaPQW0M/w720-h480-cfill-q80/taste/2016/11/lamb-meatball-saganaki-105732-1.jpeg',
        ingredient: [
            'Lamb mince',
            'Risoni',
            'Breadcrumbs',
            'Egg',
            'Oregano',
            'Onion',
            'Garlic',
            'Dry white wine',
            'Diced tomatoes',
            'Beef stock',
            'Parsley',
            'Feta and Parsley (to serve)',
        ],
        method:[
            'Bring pot of water to boil',
            'Place in a bowl; mince, breadcrumbs, egg, oregano and 1/3 of the onion. Season with salt and pepper. Combine well, roll into balls',
            'Heat oil in the pot over medium-high heat. Cook meatballs, in batches, turning, until browned all over.',
            'Heat oil in pan over medium heat. Add remaining onion. Cook, stirring, until onion is softened. Add garlic. Cook for 1 minute.',
            'Add white wine. Simmer, stirring, for 1 minute. Stir in tomatoes and stock. Add back your meatballs. Cover. Bring to the boil. Reduce heat to low. Simmer, covered, for 10 minutes',
            'Add your risoni to salted boiling pot of water, drain when complete',
            'Serve Meatballs over risoni. Optionally garnish with feta and corriander.'
        ],
    },
    {
        title: 'Vietnamese Pork Mince',
        desc: 'Simple dish, simple foods, elevated flavours. You do not want to pass on this recipe.',
        image: 'https://poshjournal.com/wp-content/uploads/2020/08/vietnamese-caramelized-pork-bowls-5.jpg',
        ingredient: [
        '500g pork mince',
        'Fish sauce',
        'Lemongrass',
        'Soy sauce',
        'Brown sugar',
        'White onion',
        'Red onion',
        'Cucumber',
        'Coriander',
        'Rice'
        ],
        method: [
            'Cook rice or noodles put to side',
            'Add oil to pan cook onion till soften. Add and break up mince untill cook through',
            'Add fish sauce, lemongrass, soy sauce and brown sugar. Mix to combine.',
            'Add meat onto bed of rice, add your toppings sliced red onion, sliced cucumber, corriander and spring onion. Enjoy!'
        ],
    },
    {
        title: 'Teriyaki Salmon',
        desc: 'Simple dish, simple foods, elevated flavours. You do not want to pass on this recipe.',
        image: 'https://theresalwayspizza.com/assets/media/242Teriyaki%20Salmon.jpg',
        ingredient: [
            '2 1/2 lbs salmon filet',
            '3 Tbsp teriyaki sauce',
            '3 Tbsp hoisin sauce',
            '3 Tbsp soy sauce',
            '1 Tbsp white vinegar',
            '1 Tbsp sesame oil',
            '1/3 cup packed light brown sugar',
            '2 large or 3 medium garlic cloves, minced',
            '2 tsp freshly grated ginger, or 1/2 tsp ground ginger',
            'sesame seeds',
            'green onion',
            'rice'
        ],
        method: [
            'Cook rice or noodles put to side',
            'Add oil to pan cook onion till soften. Add and break up mince untill cook through',
            'Add fish sauce, lemongrass, soy sauce and brown sugar. Mix to combine.',
            'Add meat onto bed of rice, add your toppings sliced red onion, sliced cucumber, corriander and spring onion. Enjoy!'
        ],
    },
    {
        title: 'Chicken and Rice',
        desc: 'Simple dish, simple foods, elevated flavours. You do not want to pass on this recipe.',
        image: 'https://lh4.googleusercontent.com/0e5wzOz0ZQykkgtgWEh-9oolJRGmeDfjn_JXzTMg_FgHNaqr5_gFk1rf5GuNGEJMqz7rPqQi_A0KtmhFzBWuzJavrusYzrKkFnqB_clb6WOPJo38gxt3_eS0fLLpkI8KuZcNK9yR',
        ingredient: [
            'garlic powder',
            'onion powder',
            'smoked paprika',
            'cumin',
            'chicken breast',
            'rice',
            'salt and pepper',
            'green onion (optional)',
        ],
        method: [
            'Cook rice',
            'butterfly chicken and beat to tenderise the meat. coat with seasoning and salt and pepper.',
            'Oil pan and cook chicken on medium heat. cook 3-5 min on both sides or until cook through',
            'Serve chicken over rice and garnish with spring onion'
        ],
    },
    {
        title: 'Chicken chickpea salad ',
        desc: 'Healthy, filling and delicious? This is definitly one to add to your rotation. Trust me. ',
        image: 'https://images.unsplash.com/photo-1505576633757-0ac1084af824?q=80&w=2835&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ingredient: [
            'chicken breast',
            'chickpea',
            'lettuce',
            'tomato',
            'cucumber',
            'red onion',
            'smoked paprika',
            'garlic powder',
            'onion powder',
            'cumin',
            'oregano',
            'lemon juice',
        ],
        method: [
            'Butterfly chicken and beat to tenderise the meat. coat with salt and pepper and seasonings.',
            'Oil pan and cook chicken on medium heat. cook 3-5 min on both sides or until cook through',
            'Add vegetables in a bowl. Add lemon juice and olive oil.',
            'Dice chicken and add to salad mixture. Serve immediately or let cool first before consuming.',
        ],
    },
];
export default recipeData;