const recipeData = [
    {
        title: 'Burito Bowls',
        desc: 'One of my all-time favorite go-to recipes is a flavorful and satisfying taco mince bowl. Seasoned with taco mix, the minced meat is served over a bed of fluffy rice, and complemented by creamy guacamole and a medley of fresh vegetables. This dish is quick to prepare, bursting with vibrant flavors, and a sure hit for any meal!',
        image: 'https://www.coles.com.au/content/dam/coles/cusp/recipes-inspiration/pvx/July-23-PVX-Burrito-Bowl-976x549.jpg',
        ingredient: [
            '500g Beef Mince',
            '20g Taco Seasoning Mix',
            '1 1/2 Red Kidney Beans ',
            '1 1/2 cups Rice',
            '1 Avocado',
            '1/2 Red Onion',
            '1 Lime',
            '1/4 cup Coriander',
            '1 Tomato',
            '2 cups Lettuce',
            '1 cup corn',
        ],
        method: [
            'Peel avocado cut into cubes, finely dice your red onion and coriander. Place into your bowl and add juice of 1 lime, salt and pepper. Break up avocado and mix well. Set guacamole in fridge until ready to serve.',
            'Wash the rice thoroughly and cook per intructions.',
            'While the rice is cooking, oil the pan on medium-high heat. Add your onion and cook till golden (1-2 min). Then add your beef mince, break up the beef mince and keep moving to ensure every bit of the mince browned.',
            'Add taco mix and water. Mix in well. Let simmer for about 10-15 min.',
            'Serve over the rice and add shredded lettuce, rinsed corn, diced tomato and guacamole. Enjoy!',
        ],
    },
    {
        title:`Lola's Pork Adobo`,
        desc:'This recipe holds a special place in my heart, as it was passed down from my beloved Lola (grandma). The key to its irresistible flavor is marinating the pork overnight, allowing the vegeta to fully infuse the meat. Also adding vinegar before the other remaining ingredients. I absolutely love this dish for its delicious and tasty results. While I am currently refining this recipe, it remains a family favorite that never fails to impress.',
        image:'https://images.unsplash.com/photo-1612156723470-10f426219f63?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ingredient: [
            '1 1/2 cups Rice',
            '750g Pork Rashers',
            '6 Garlic Cloves',
            '1 Onion',
            '1/2 cup Vinegar',
            '1/4 cup Soy Sauce',
            '3 Bay leaves',
            '1 Bunch Lemon Grass',
            '1/3 cup Vegeta',
            '1 Tbsp Grinded Black Peppercorns',
            '2 Tbsp brown sugar',
        ],
        method:[
            'Marinade pork in vegeta for 12 hours or overnight.',
            'Wash the rice thoroughly and start cooking per intructions.',
            'Place pot on medium-high, add oil to sautee onion until translucent. Add garlic and cook for 1 minute further.',
            'Cook pork rashers until it completly changes colour',
            'Add vinegar and let the pot sit for 30 seconds. Then add soy sauce, bay leaves, lemongrass and pepper. Mix till combined well.',
            'Add boiling water then simmer until you reach desired consistency',
            'Serve over rice and enjoy!'
        ],
    },
    {
        title: 'Lamb Saganaki',
        desc:'Transform everyday ingredients into a culinary delight with this inspired lamb mince dish. These succulent lamb meatballs, crafted from simple pantry staples, are a guaranteed family pleaser. Simmered in a delicious tomato and white wine sauce, their rich, savory flavor and tender texture make them a standout at any meal, bringing a fresh twist to familiar favorites.',
        image:'https://img.taste.com.au/ApaPQW0M/w720-h480-cfill-q80/taste/2016/11/lamb-meatball-saganaki-105732-1.jpeg',
        ingredient: [
            '500g lamb mince',
            '1/2 packet Risoni',
            '3/4 cup Breadcrumbs',
            '1 Egg',
            '1/4 cup Oregano',
            '1 Brown Onion',
            '3 Garlic Cloves',
            '1/2 cup Dry white wine',
            '400g Diced tomatoes',
            '1/2 cup Beef stock',
            '50g Feta',
            'small bunch of Parsley',
        ],
        method:[
            'Bring pot of water to boil',
            'Add your risoni to salted boiling pot of water, drain when complete',
            'Place in a bowl; mince, breadcrumbs, egg, oregano and 1/3 of the onion. Season with salt and pepper. Combine well, roll into balls',
            'Heat oil in the pot over medium-high heat. Cook meatballs, in batches, turning, until browned all over. Put aside for later use.',
            'Add oil in pan if necessary. Add remaining onion. Cook, stirring, until onion is softened. Add garlic. Cook for 1 minute.',
            'Add white wine. Simmer, stirring, for 1 minute. Stir in diced tomatoes and stock. Add back your meatballs. Cover. Bring to the boil. Reduce heat to low. Simmer, covered, for 10 minutes',
            'Serve Meatballs over risoni. Optionally garnish with feta and parsely.'
        ],
    },
    {
        title: 'Vietnamese Pork Mince',
        desc: 'Simple dish, simple ingredients, elevated flavors—this Vietnamese pork mince recipe is a must-try. Bursting with vibrant and authentic tastes, it is an easy-to-make dish that delivers a delightful culinary experience. You do not want to pass on this recipe.',
        image: 'https://poshjournal.com/wp-content/uploads/2020/08/vietnamese-caramelized-pork-bowls-5.jpg',
        ingredient: [
        '500g pork mince',
        '1 cup Rice',
        '2 tsp Ginger',
        '2 Garlic cloves',
        '2 Tbsp Fish sauce',
        '3 Tbsp Brown sugar',
        'Small bunch Lemongrass',
        '1/2 Brown onion',
        '1/2 Cucumber',
        '1 Tomato', 
        ],
        method: [
            'Wash the rice thoroughly and cook per intructions.',
            'Add oil to pan cook onion, ginger and garlic cook for 2 minutes. Add mince and break up untill cooked through',
            'Add fish sauce, lemongrass and brown sugar. Mix to combine and avoid touching for 2 min to caramalise the mince. stir again and leave for a further 30 seconds.',
            'Add meat onto bed of rice, top with your sliced cucumber, spring onion and tomato. Enjoy!'
        ],
    },
    {
        title: 'Teriyaki Salmon',
        desc: 'Indulge in the simplicity of this easy Asian glazed salmon. Marinate ahead of time for maximum flavor infusion, then enjoy the effortless cooking process that yields a dish bursting with savory-sweet goodness. With its straightforward steps and impressive taste, this recipe will not disappoint. Perfect for busy days or when you crave a delicious yet simple meal.',
        image: 'https://theresalwayspizza.com/assets/media/242Teriyaki%20Salmon.jpg',
        ingredient: [
            '500g Salmon filet',
            '2 tsp Ginger',
            '2 tsp Garlic clove',
            '1 1/2 Tbsp Soy sauce',
            '2 Tbsp Oyster sauce',
            '2 Tbsp Sweet chilli sauce ',
            'Sesame seeds',
            'Green onion',
            '1 cup Rice'
        ],
        method: [
            'Whisk together ginger, garlic, soy sauce, oyster sauce and sweet chilli sauce. Add salmon and coat. Cover and marinate for 30 minutes or overnight.',
            'Wash the rice thoroughly and cook per intructions.',
            'Pre heat the oven to 180º degrees. Cook salmon in oven for 7 min, check on salmon and see if you need to oil it. Cook for a further 3 min ',
            'Add salmon onto bed of rice, add your toppings sliced spring onion and sesame seeds. Enjoy!'
        ],
    },
    {
        title: 'Italian Rice Pilaf',
        desc: 'Experience the best of both worlds with this Italian beef rice pilaf—a delightful fusion of creamy risotto and rich Bolognese flavors. Tender beef, aromatic herbs, and savory tomato sauce come together harmoniously with perfectly cooked rice, creating a dish that embodies comfort and satisfaction. It is everything you love about risotto and Bolognese in one flavorful bite, making it a surefire hit for any meal.',
        image: 'https://lh4.googleusercontent.com/0e5wzOz0ZQykkgtgWEh-9oolJRGmeDfjn_JXzTMg_FgHNaqr5_gFk1rf5GuNGEJMqz7rPqQi_A0KtmhFzBWuzJavrusYzrKkFnqB_clb6WOPJo38gxt3_eS0fLLpkI8KuZcNK9yR',
        ingredient: [
            '500g Beef mince',
            '1  1/2 cups Rice',
            '2 Tbsp Olive oil',
            '2 Garlic cloves minced',
            '1 Brown onion diced',
            '1 Carrot diced',
            '1 Celery stalk diced',
            '1 1/2 tsp Fennel seeds',
            '400g Crushed tomatoes',
            '2 1/2 cups Beef stock',
            '1 Bay leaf',
            '2 tsp Worcestershire sauce',
            '2 Tomatoes diced',
        ],
        method: [
            'Heat oil in large pot over high heat. Add garlic, onioin carrot, celery, fennel seeds. Cook until onion is translucent.',
            'Add Beef mince, break up until it turns from pink to brown. add salt and pepper to season.',
            'Add the unwashed rice and mix into your pot. Add remaining ingredients. Stir everything together, then when it comes to a simmer, cover with a lid and turn the heat doen to low (do not touch).',
            'Cook for 22 minutes or until rice is tender. remove from heat and rest keeping covered for 5 minutes - the rice will soften further.',
            'Serve with optinal toppings and Enjoy!',
        ],
    },
    {
        title: 'Chicken chickpea salad ',
        desc: 'Looking for a healthy, filling, and delicious meal that is easy to make? Look no further than this chicken chickpea salad. It is a definite addition to your meal rotation, offering a perfect balance of nutrients and flavors. You can easily substitute rotisserie chicken with shredded, seasoned chicken breast. Plus, keep an eye out for discounted rotisserie chickens at the end of the day for a real last-minute meal saver. Trust me, this salad is a winner!.',
        image: 'https://images.unsplash.com/photo-1505576633757-0ac1084af824?q=80&w=2835&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        ingredient: [
            'Rotisserie Chicken',
            '250g Feta and Olive blend.',
            '1 can Chickpea',
            '1 can White beans',
            '1 bunch Corriander',
            '1 bunch Parsley',
            '1 punnet Cherry Tomato',
            '1 Capsicum',
            '1/4 Red onion',
            '1/2 cup Olive oil',
            '1/4 red wine vinegar',
            '2 lemons',
            '1/2 tsp dijon',
            '2 Garlic cloves',
            'Pinch of Red pepper flakes.',
        ],
        method: [
            'Break down and shred the chicken.',
            'In a big bowl, whisk together olive oil, red wine vinegar, lemon juice, mustard, salt, garlic, red pepper flakes',
            'Toss remaining ingredients in bowl. Mix well. Taste and balance salt and pepper. Enjoy!',
        ],
    },
];
export default recipeData;